"""Tests for the public ``GET /api/verify/{invoice_id}`` endpoint.

The endpoint is intentionally unauthenticated and intentionally
omits all PII. These tests both prove the happy path AND prove
the negative space &mdash; e.g. that vendor names and amounts never
leak into the response body.
"""
from __future__ import annotations

from datetime import date, datetime

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.database import Base, get_db
import app.models  # noqa: F401
from app.models import Enterprise, Invoice, MSME
from app.routes.verification import router as verification_router


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------
@pytest.fixture()
def shared_engine():
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    try:
        yield engine
    finally:
        Base.metadata.drop_all(bind=engine)
        engine.dispose()


@pytest.fixture()
def SessionLocal(shared_engine):
    return sessionmaker(bind=shared_engine, autoflush=False, autocommit=False)


@pytest.fixture()
def app(SessionLocal):
    app = FastAPI()

    def _override_get_db():
        db = SessionLocal()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = _override_get_db
    app.include_router(verification_router, prefix="/api")
    return app


@pytest.fixture()
def client(app):
    with TestClient(app) as c:
        yield c


def _seed_invoice(SessionLocal, *, state="VERIFIED") -> int:
    s = SessionLocal()
    try:
        ent = Enterprise(name="Bharat Industries", pan="AAACB1234D")
        s.add(ent)
        s.flush()
        msme = MSME(
            enterprise_id=ent.id,
            vendor_name="Sharma Steel Works",
            gstin="29ABCDE1234F1Z5",
        )
        s.add(msme)
        s.flush()
        invoice = Invoice(
            vendor_name="Sharma Steel Works",
            gstin="29ABCDE1234F1Z5",
            invoice_number="INV-SECRET-001",
            invoice_amount=999_999.99,
            invoice_date=date(2026, 3, 21),
            date_of_acceptance=date(2026, 3, 21),
            deadline_43bh=date(2026, 5, 5),
            status=state,
            state=state,
            confidence_score=0.94,
            enterprise_id=ent.id,
            msme_id=msme.id,
            verified_at=datetime(2026, 3, 21, 14, 1, 9),
        )
        s.add(invoice)
        s.commit()
        return invoice.id
    finally:
        s.close()


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------
class TestVerifyPublicHappyPath:
    def test_returns_sanitized_envelope(self, client, SessionLocal):
        invoice_id = _seed_invoice(SessionLocal)
        r = client.get(f"/api/verify/{invoice_id}")
        assert r.status_code == 200
        body = r.json()
        assert body["invoice_id"] == invoice_id
        assert body["state"] == "VERIFIED"
        assert body["watermark"] == "Generated by TrustAudit"
        assert isinstance(body["audit_hash"], str)
        assert len(body["audit_hash"]) == 64
        # Hash is hex
        int(body["audit_hash"], 16)
        assert body["confidence_score"] == 0.94
        assert body["date_of_acceptance"] == "2026-03-21"
        assert body["extraction_model"] == "gemini-flash-latest"

    def test_no_pii_in_response(self, client, SessionLocal):
        invoice_id = _seed_invoice(SessionLocal)
        r = client.get(f"/api/verify/{invoice_id}")
        body_text = r.text
        # The vendor name, GSTIN, invoice number, and amount must NEVER appear.
        assert "Sharma Steel" not in body_text
        assert "29ABCDE1234F1Z5" not in body_text
        assert "INV-SECRET-001" not in body_text
        assert "999999" not in body_text
        assert "Bharat Industries" not in body_text
        assert "AAACB1234D" not in body_text

        # Defensive: ensure response keys are exactly the allowed set
        body = r.json()
        allowed_keys = {
            "invoice_id",
            "audit_hash",
            "state",
            "confidence_score",
            "date_of_acceptance",
            "extracted_at",
            "extraction_model",
            "watermark",
        }
        assert set(body.keys()) == allowed_keys

    def test_submitted_state_also_visible(self, client, SessionLocal):
        invoice_id = _seed_invoice(SessionLocal, state="SUBMITTED_TO_GOV")
        r = client.get(f"/api/verify/{invoice_id}")
        assert r.status_code == 200
        assert r.json()["state"] == "SUBMITTED_TO_GOV"

    def test_audit_hash_is_deterministic(self, client, SessionLocal):
        invoice_id = _seed_invoice(SessionLocal)
        r1 = client.get(f"/api/verify/{invoice_id}")
        r2 = client.get(f"/api/verify/{invoice_id}")
        assert r1.json()["audit_hash"] == r2.json()["audit_hash"]


class TestVerifyPublic404:
    def test_nonexistent_invoice_returns_404(self, client):
        r = client.get("/api/verify/9999")
        assert r.status_code == 404

    def test_pending_state_is_hidden(self, client, SessionLocal):
        invoice_id = _seed_invoice(SessionLocal, state="PENDING")
        r = client.get(f"/api/verify/{invoice_id}")
        # Don't leak existence of unverified invoices
        assert r.status_code == 404

    def test_disputed_state_is_hidden(self, client, SessionLocal):
        invoice_id = _seed_invoice(SessionLocal, state="DISPUTED")
        r = client.get(f"/api/verify/{invoice_id}")
        assert r.status_code == 404

    def test_needs_info_is_hidden(self, client, SessionLocal):
        invoice_id = _seed_invoice(SessionLocal, state="NEEDS_INFO")
        r = client.get(f"/api/verify/{invoice_id}")
        assert r.status_code == 404
