"""baseline from models.py

Revision ID: 7592483b522b
Revises: 
Create Date: 2026-04-07 18:59:17.510653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7592483b522b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('demo_color_hex', sa.String(length=9), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprises_id'), 'enterprises', ['id'], unique=False)
    op.create_index(op.f('ix_enterprises_pan'), 'enterprises', ['pan'], unique=False)
    op.create_table('rate_limits',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('msmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('udyam_number', sa.String(length=20), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('primary_phone_e164', sa.String(length=20), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msmes_enterprise_id'), 'msmes', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_msmes_gstin'), 'msmes', ['gstin'], unique=False)
    op.create_index(op.f('ix_msmes_id'), 'msmes', ['id'], unique=False)
    op.create_index(op.f('ix_msmes_primary_phone_e164'), 'msmes', ['primary_phone_e164'], unique=False)
    op.create_index(op.f('ix_msmes_state_code'), 'msmes', ['state_code'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_amount', sa.Float(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('date_of_acceptance', sa.Date(), nullable=False),
    sa.Column('deadline_43bh', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('challan_image_url', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('msme_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('missing_fields', sa.Text(), nullable=True),
    sa.Column('detected_edge_cases', sa.Text(), nullable=True),
    sa.Column('raw_image_sha256', sa.String(length=64), nullable=True),
    sa.Column('compliance_pdf_url', sa.String(length=512), nullable=True),
    sa.Column('submitted_to_gov_at', sa.DateTime(), nullable=True),
    sa.Column('govt_submission_receipt', sa.String(length=255), nullable=True),
    sa.Column('annotated_image_b64', sa.Text(), nullable=True),
    sa.Column('annotated_boxes_json', sa.Text(), nullable=True),
    sa.Column('annotated_width', sa.Integer(), nullable=True),
    sa.Column('annotated_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['msme_id'], ['msmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_enterprise_id'), 'invoices', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_msme_id'), 'invoices', ['msme_id'], unique=False)
    op.create_index(op.f('ix_invoices_raw_image_sha256'), 'invoices', ['raw_image_sha256'], unique=False)
    op.create_index(op.f('ix_invoices_state'), 'invoices', ['state'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('msme_id', sa.Integer(), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('primary_phone_e164', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('pwd_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['msme_id'], ['msmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_enterprise_id'), 'users', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_msme_id'), 'users', ['msme_id'], unique=False)
    op.create_index(op.f('ix_users_primary_email'), 'users', ['primary_email'], unique=True)
    op.create_index(op.f('ix_users_primary_phone_e164'), 'users', ['primary_phone_e164'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('challan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_ocr_json', sa.Text(), nullable=True),
    sa.Column('vlm_response_json', sa.Text(), nullable=True),
    sa.Column('detected_edge_cases_json', sa.Text(), nullable=True),
    sa.Column('handler_actions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challan_events_event_type'), 'challan_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_challan_events_id'), 'challan_events', ['id'], unique=False)
    op.create_index(op.f('ix_challan_events_invoice_id'), 'challan_events', ['invoice_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    op.create_index(op.f('ix_disputes_invoice_id'), 'disputes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('raw_profile_json', sa.Text(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_identity_user_provider')
    )
    op.create_index(op.f('ix_user_identities_id'), 'user_identities', ['id'], unique=False)
    op.create_index(op.f('ix_user_identities_provider_user_id'), 'user_identities', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_destination'), 'verification_codes', ['destination'], unique=False)
    op.create_index(op.f('ix_verification_codes_id'), 'verification_codes', ['id'], unique=False)
    op.create_index(op.f('ix_verification_codes_user_id'), 'verification_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_codes_user_id'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_id'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_destination'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_provider_user_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_id'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_invoice_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_challan_events_invoice_id'), table_name='challan_events')
    op.drop_index(op.f('ix_challan_events_id'), table_name='challan_events')
    op.drop_index(op.f('ix_challan_events_event_type'), table_name='challan_events')
    op.drop_table('challan_events')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_primary_phone_e164'), table_name='users')
    op.drop_index(op.f('ix_users_primary_email'), table_name='users')
    op.drop_index(op.f('ix_users_msme_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_enterprise_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_invoices_state'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_raw_image_sha256'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_msme_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_enterprise_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_msmes_state_code'), table_name='msmes')
    op.drop_index(op.f('ix_msmes_primary_phone_e164'), table_name='msmes')
    op.drop_index(op.f('ix_msmes_id'), table_name='msmes')
    op.drop_index(op.f('ix_msmes_gstin'), table_name='msmes')
    op.drop_index(op.f('ix_msmes_enterprise_id'), table_name='msmes')
    op.drop_table('msmes')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_enterprises_pan'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_id'), table_name='enterprises')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
