"""Public, no-auth invoice verification endpoint.

This is what the QR code on the printed compliance PDF resolves to.
A tax officer can scan the QR, hit ``GET /api/verify/{invoice_id}``,
and confirm that the document was generated by TrustAudit and matches
the canonical record &mdash; without exposing any PII (no vendor name,
no GSTIN, no amount).

Returns 404 unless the invoice exists and is in ``VERIFIED`` or
``SUBMITTED_TO_GOV`` state.

The router is exported as ``router`` and is registered on
``main.py`` by W10 &mdash; this module never touches ``main.py``.
"""
from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session as DBSession

from ..database import get_db
from ..models import Invoice
from ..services.pdf import ComplianceFormContext, compute_audit_hash
from ..services.state_machine import InvoiceState

logger = logging.getLogger(__name__)

router = APIRouter(tags=["verification"])


# Public-safe states &mdash; everything else 404s.
_PUBLICLY_VISIBLE_STATES = frozenset(
    {InvoiceState.VERIFIED.value, InvoiceState.SUBMITTED_TO_GOV.value}
)


class PublicVerificationResponse(BaseModel):
    """Sanitized verification envelope.

    Intentionally omits vendor_name, amount, GSTIN, address, dispute
    history &mdash; anything that could be PII or competitively
    sensitive. Only includes enough fields to (a) prove the document
    came from TrustAudit, (b) show the assessor that the chain of
    custody is intact, and (c) confirm the date of acceptance lines
    up with the printed form.
    """

    invoice_id: int
    audit_hash: str
    state: str
    confidence_score: float
    date_of_acceptance: Optional[str] = None
    extracted_at: Optional[str] = None
    extraction_model: str
    watermark: str = "Generated by TrustAudit"


def _build_minimal_context(invoice: Invoice) -> ComplianceFormContext:
    """Reconstruct just enough fields for :func:`compute_audit_hash`.

    The hash must match what the form-render path produces, so we use
    the same canonical field set even though we never expose them.
    """
    return ComplianceFormContext(
        invoice_id=invoice.id,
        enterprise_name="",
        enterprise_pan="",  # not exposed
        msme_vendor_name="",
        msme_gstin=invoice.gstin or "",
        msme_udyam=None,
        invoice_number=invoice.invoice_number or "",
        invoice_date=invoice.invoice_date.isoformat() if invoice.invoice_date else "",
        invoice_amount_inr=float(invoice.invoice_amount or 0.0),
        date_of_acceptance=(
            invoice.date_of_acceptance.isoformat() if invoice.date_of_acceptance else ""
        ),
        deadline_43bh=invoice.deadline_43bh.isoformat() if invoice.deadline_43bh else "",
        days_remaining_at_generation=0,
        confidence_score=float(invoice.confidence_score or 0.0),
        extraction_model="gemini-flash-latest",
        extracted_at=(
            invoice.verified_at.isoformat()
            if invoice.verified_at
            else (invoice.created_at.isoformat() if invoice.created_at else "")
        ),
    )


@router.get(
    "/verify/{invoice_id}",
    response_model=PublicVerificationResponse,
    response_model_exclude_none=False,
)
def verify_invoice_public(
    invoice_id: int,
    db: DBSession = Depends(get_db),
) -> PublicVerificationResponse:
    invoice = db.query(Invoice).filter(Invoice.id == invoice_id).one_or_none()
    if invoice is None:
        raise HTTPException(status_code=404, detail="Invoice not found")
    if invoice.state not in _PUBLICLY_VISIBLE_STATES:
        # Don't leak the existence of unverified invoices.
        raise HTTPException(status_code=404, detail="Invoice not found")

    ctx = _build_minimal_context(invoice)
    audit_hash = compute_audit_hash(ctx)

    return PublicVerificationResponse(
        invoice_id=invoice.id,
        audit_hash=audit_hash,
        state=invoice.state,
        confidence_score=round(float(invoice.confidence_score or 0.0), 4),
        date_of_acceptance=(
            invoice.date_of_acceptance.isoformat()
            if invoice.date_of_acceptance
            else None
        ),
        extracted_at=(
            invoice.verified_at.isoformat()
            if invoice.verified_at
            else (invoice.created_at.isoformat() if invoice.created_at else None)
        ),
        extraction_model="gemini-flash-latest",
        watermark="Generated by TrustAudit",
    )
